name: 运行主程序
on: [push, workflow_dispatch]
jobs:
  run:
    name: 运行主程序
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            command: sudo bash reinstall.sh --debug
          - os: windows-latest
            command: ./reinstall.bat --debug
    runs-on: ${{ matrix.os }}
    steps:
      - run: |
          git config --global core.autocrlf false
      - uses: actions/checkout@v4
      - shell: bash # https://github.com/actions/runner-images/issues/6668
        run: |
          ${{ matrix.command }} centos 7
          ${{ matrix.command }} alma-8
          ${{ matrix.command }} rocky 8
          ${{ matrix.command }} fedora
          ${{ matrix.command }} ubuntu
          ${{ matrix.command }} debian 12
          ${{ matrix.command }} alpine
          ${{ matrix.command }} dd --img=https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.3.8.tar.xz

          # 测试 cloud image
          ${{ matrix.command }} centos --ci
          ${{ matrix.command }} alma --ci
          ${{ matrix.command }} rocky --ci
          ${{ matrix.command }} fedora-38 --ci
          ${{ matrix.command }} ubuntu 22.04 --ci
          ${{ matrix.command }} debian --ci
          ${{ matrix.command }} opensuse
          ${{ matrix.command }} arch
          ${{ matrix.command }} gentoo

          # 测试失败例子
          ! ${{ matrix.command }} wrong-os
          ! ${{ matrix.command }} dd --img=https://github.com/
          ! ${{ matrix.command }} windows --iso=https://github.com/ --image-name=abc
